# Generated by Django 5.0.7 on 2024-07-25 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_location', models.CharField(default='db.sqlite3', max_length=255)),
                ('current_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_settings', to='Rotation.tech')),
                ('previous_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_settings', to='Rotation.tech')),
            ],
        ),
    ]
