# Generated by Django 5.0.7 on 2024-07-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='database_location',
            field=models.CharField(default='/home/aeon/code/school/spencer/django/NexTech/db.sqlite3', max_length=255),
        ),
    ]
