# Generated by Django 5.0.7 on 2024-07-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rotation', '0002_alter_settings_database_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='database_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
