# Generated by Django 5.0.7 on 2024-07-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rotation', '0003_alter_settings_database_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='database_location',
        ),
    ]
