# Generated by Django 5.0.7 on 2024-07-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rotation', '0004_remove_settings_database_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='settings',
            name='database_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
