# Generated by Django 5.0.7 on 2024-07-26 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rotation', '0005_alter_settings_options_settings_database_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.CreateModel(
            name='TechAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rotation.tech')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
